const actionsTypes = {
    'GENERATE_CANDIDATE_MOVES' : 'GENERATE_CANDIDATE_MOVES',
    'CLEAR_CANDIDATE_MOVES' : 'CLEAR_CANDIDATE_MOVES',
    'NEW_MOVE'  : 'NEW_MOVE',
    'SAVE_PIECE_OLD_NEW' : 'SAVE_PIECE_OLD_NEW',
    'SWAP_TURN':'SWAP_TURN',
    "INIT_GAME":"INIT_GAME",
} 
export default actionsTypes